name: hw-hedgehog
version: '0.1.0.1'
synopsis: Extra hedgehog functionality
description: Extra hedgehog functionality.
category: Test
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2017-2018 John Ky
license: BSD3
github: haskell-works/hw-hedgehog
tested-with: GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.2

extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Hedgehog
  - HaskellWorks.Hedgehog.Gen
  dependencies:
  - base >=4.8 && <5
  - hedgehog >= 0.5 && < 0.7
  - vector >= 0.10 && < 0.13

tests:
  hw-hedgehog-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hw-hedgehog
