defaults: &defaults
  working_directory: ~/build
  docker:
    - image: quay.io/haskell_works/stack-build-cabal:2018-01-29

  steps:
    - checkout

    - run:
        name: Remove Cabal file
        command: rm -f *.cabal

    - run:
        name: Copying scripts
        command: |
          mkdir -p ~/.local/bin
          cp ./scripts/* ~/.local/bin

    - run:
        name: Query resolver & ghc version
        command: |
          resolver "$(resolver $LTS)" > resolver.version
          ghc-version $(cat resolver.version) >  ghc.version

    - run:
        name: Find all sub-projects
        command: projects-summary > projects.summary

    ##### Building library
    - restore_cache:
        keys:
          - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "projects.summary" }}--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml" }}
          - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "projects.summary" }}--{{ checksum "package.yaml" }}
          - stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "projects.summary" }}--
          - stack--{{ checksum "ghc.version" }}--X

    - run:
        name: Stack setup
        command: stack setup --resolver ${LTS}

    - save_cache:
        key:    stack--{{ checksum "ghc.version" }}--X
        paths:  [~/.stack, ~/project/.stack-work]

    - run:
        name: Building dependencies
        command: |
          stack build --resolver ${LTS} --dependencies-only
          stack build --resolver ${LTS} --dependencies-only --test --no-run-tests

    - save_cache:
        key:    stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "projects.summary" }}--{{ checksum "package.yaml" }}
        paths:  [~/.stack, ~/project/.stack-work]

    - run: stack build --resolver ${LTS} --test --no-run-tests

    - save_cache:
        key:    stack--{{ checksum "ghc.version" }}--{{ .Environment.CACHE_VERSION }}--{{ checksum "resolver.version" }}--{{ checksum "projects.summary" }}--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml" }}
        paths:  [~/.stack, ~/project/.stack-work]

    ##### Running tests
    - run:
        name: Running tests against latest on hackage
        command: stack test --resolver ${LTS}

version: 2.0
jobs:
  lts-10:
    environment:
      - LTS: "lts-10"
    <<: *defaults

  lts-11:
    environment:
      - LTS: "lts-11"
    <<: *defaults

  lts-12:
    environment:
      - LTS: "lts-12"
    <<: *defaults

  nightly:
    environment:
      - LTS: "nightly"
    <<: *defaults

  release:
    docker:
      - image: quay.io/haskell_works/stack-build-cabal:2018-01-29

    steps:
      - deploy:
          command: |
            echo "Hello"
            # if [ "$CIRCLE_PROJECT_USERNAME" == "haskell-works" ]; then
            #   if [[ "$CIRCLE_BRANCH" == master ]]; then
            #     when tag autotag
            #   elif [[ "$CIRCLE_TAG" =~ v.* ]]; then
            #     publish
            #   fi
            # fi

workflows:
  version: 2
  multiple-ghcs:
    jobs:
      - lts-10
      - lts-12
      - lts-11:
          requires:
            - lts-10
            - lts-12
      - nightly:
          requires:
            - lts-10
            - lts-12
      - release:
          requires:
            - lts-12
            - lts-11
            - lts-10
            - nightly
          filters:
            branches:
              only: master
